name: CI

on:
  push:
    branches: [ main ]  # O workflow será executado em cada "push" na branch "main".
  pull_request:
    branches: [ main ]  # O workflow será executado em cada "pull request" direcionado à branch "main".

jobs:
  build:
    runs-on: ubuntu-latest  # Define o sistema operacional para executar o workflow.
    permissions:
      contents: read
      pages: write
      id-token: write  # Necessário para autenticação OIDC
    
    steps:
      - uses: actions/checkout@v3  # Faz o "checkout" do código do repositório para a máquina virtual.

      - name: Executar testes
        run: |
          echo "Nenhum teste implementado ainda. Adicione testes em script.js!"
          echo "Podemos adicionar testes com Jest ou Cypress no futuro."
          echo "Testes simulados aprovados"
          exit 0  # Simula testes passando
      
       - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'

      - name: Deploy para GitHub Pages
        if: github.ref == 'refs/heads/main'  # Só executa o deploy quando o commit for na branch main.
        uses: actions/deploy-pages@v2
        