name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write  # Permissão necessária para OIDC

    steps:
      # Passo 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Executar testes (simulado)
      - name: Run tests
        run: |
          echo "Nenhum teste implementado ainda. Adicione testes em script.js!"
          echo "Podemos adicionar testes com Jest ou Cypress no futuro."
          echo "Testes simulados aprovados"
          exit 0

      # Passo 3: Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Passo 4: Build do projeto (simulado - substitua pelo seu build real)
      - name: Build project
        run: |
          echo "Simulando construção do projeto..."
          mkdir -p dist
          echo "<html><body><h1>Meu Site</h1></body></html>" > dist/index.html

      - name: Upload Regular Artifact (Workaround)
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

      # Passo 5: Upload do artefato para deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'  # Pasta contendo os arquivos para deploy

      # Passo 6: Deploy (apenas na branch main)
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v3