name: CI/CD Pipeline


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # --- PASSO ADICIONADO PARA RESOLVER O ERRO ---
      - name: Force download upload-artifact@v4
        uses: actions/upload-artifact@v4
        with:
          name: temp
          path: /tmp/empty
          if-no-files-found: ignore

      # Passo 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Executar testes (simulado)
      - name: Run tests
        run: |
          echo "Testes simulados (adicione testes reais depois!)"
          exit 0

      # Passo 3: Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Passo 4: Build do projeto
      - name: Build project
        run: |
          mkdir -p dist
          echo "<html><body><h1>Site Funcionando!</h1></body></html>" > dist/index.html

      # Passo 5: Upload do artefato
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'

      # Passo 6: Deploy (apenas na main)
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v3